import { render, screen } from "@testing-library/react";
import type { Address } from "viem";
import type { Pool, PoolState } from "../../data/rfq/deposits";
import type { WalletPoolPositionHookState } from "../wallet/useWalletPoolPosition";
import { PoolUserPosition } from "./PoolUserPosition";
const mocks = vi.hoisted(() => ({ open: vi.fn(), switchChain: vi.fn(), useWalletPoolPosition: vi.fn() }));
vi.mock("@reown/appkit/react", () => ({ useAppKit: () => ({ open: mocks.open }) }));
vi.mock("wagmi", () => ({ useSwitchChain: () => ({ isPending: false, switchChain: mocks.switchChain }) }));
vi.mock("../wallet/useWalletPoolPosition", () => ({ useWalletPoolPosition: () => { const result: unknown = mocks.useWalletPoolPosition(); return result as { state: WalletPoolPositionHookState }; } }));
const account = "0x0000000000000000000000000000000000000001" as Address;
const wrappedBnb = "0x0000000000000000000000000000000000000020" as Address;
const asset = "0x0000000000000000000000000000000000000021" as Address;
const pool = { id: "pool", display: { name: "Test Set", description: "A test Set", sortOrder: 0 }, chain: { id: 97, name: "BSC Testnet" }, contract: { address: "0x0000000000000000000000000000000000000010" }, lpToken: { address: "0x0000000000000000000000000000000000000011", decimals: 18, symbol: "SETWISE" }, quotePolicy: { allowedLockDays: [0] }, assets: [{ address: wrappedBnb, decimals: 18, id: "WBNB", index: 0, symbol: "WBNB", weight: 1 }, { address: asset, decimals: 6, id: "USDT", index: 1, symbol: "USDT", weight: 1 }] } as Pool;
const poolState = { blockNumber: "123", chainId: 97, poolAddress: pool.contract.address, poolId: pool.id, totalValueUsd: "1000", totalSupply: { amount: "100", atomicAmount: "100000000000000000000", decimals: 18 }, contract: { wrappedNativeToken: wrappedBnb }, assets: [{ asset: "WBNB", market: { bidUsd: "600", askUsd: "602" } }, { asset: "USDT", market: { bidUsd: "1", askUsd: "1" } }] } as PoolState;
function renderState(state: WalletPoolPositionHookState) { mocks.useWalletPoolPosition.mockReturnValue({ state }); return render(<PoolUserPosition pool={pool} poolState={poolState} />); }
describe("PoolUserPosition", () => {
  beforeEach(() => vi.clearAllMocks());
  it("prompts disconnected users without requiring the public pool inputs to disappear", () => { renderState({ status: "disconnected" }); expect(screen.getByRole("heading", { name: "Connect to view your balances" })).toBeVisible(); screen.getByRole("button", { name: "Connect wallet" }).click(); expect(mocks.open).toHaveBeenCalledWith({ view: "Connect" }); });
  it("isolates a wrong network to the user section", () => { renderState({ account, actualChainId: 1, expectedChainId: 97, status: "wrong-network" }); screen.getByRole("button", { name: "Switch network" }).click(); expect(mocks.switchChain).toHaveBeenCalledWith({ chainId: 97 }); });
  it("shows mixed, claimable liquidity and keeps LP shares out of wallet balances", () => { renderState({ status: "ready", position: { account, assetBalances: [{ assetId: "WBNB", address: wrappedBnb, balance: 2n * 10n ** 18n }, { assetId: "USDT", address: asset, balance: 25_000_000n }], blockNumber: 123n, chainId: 97, nativeBalance: 500_000_000_000_000_000n, shares: { canClaim: true, locked: 4n * 10n ** 18n, lockedUntil: 1_800_000_000n, totalAttributed: 10n * 10n ** 18n, unlocked: 6n * 10n ** 18n } } }); expect(screen.getByText("~$100.00")).toBeVisible(); expect(screen.getByText("Claimable now")).toBeVisible(); expect(screen.getByText("~$1,202.00")).toBeVisible(); expect(screen.getByText("~$300.50")).toBeVisible(); expect(screen.queryByText("SETWISE", { selector: "li span" })).not.toBeInTheDocument(); });
  it("shows an unlock date for locked shares that are not yet claimable", () => { renderState({ status: "ready", position: { account, assetBalances: [{ assetId: "WBNB", address: wrappedBnb, balance: 0n }, { assetId: "USDT", address: asset, balance: 0n }], blockNumber: 123n, chainId: 97, nativeBalance: 0n, shares: { canClaim: false, locked: 3n, lockedUntil: 1_800_000_000n, totalAttributed: 3n, unlocked: 0n } } }); expect(screen.getByText(/^Unlocks /)).toBeVisible(); });
  it("labels fully unlocked liquidity without implying a claim is available", () => { renderState({ status: "ready", position: { account, assetBalances: [{ assetId: "WBNB", address: wrappedBnb, balance: 0n }, { assetId: "USDT", address: asset, balance: 0n }], blockNumber: 123n, chainId: 97, nativeBalance: 0n, shares: { canClaim: false, locked: 0n, lockedUntil: 0n, totalAttributed: 3n, unlocked: 3n } } }); expect(screen.getByText("No locked shares")).toBeVisible(); });
  it("renders a useful explicit zero-balance state", () => { renderState({ status: "zero-balance", position: { account, assetBalances: [{ assetId: "WBNB", address: wrappedBnb, balance: 0n }, { assetId: "USDT", address: asset, balance: 0n }], blockNumber: 123n, chainId: 97, nativeBalance: 0n, shares: { canClaim: false, locked: 0n, lockedUntil: 0n, totalAttributed: 0n, unlocked: 0n } } }); expect(screen.getByText("You do not hold Set shares or supported assets in this wallet yet.")).toBeVisible(); });
  it("shows a contained RPC failure", () => { renderState({ account, blockNumber: 123n, chainId: 97, error: new Error("RPC unavailable"), status: "rpc-error" }); expect(screen.getByRole("alert")).toHaveTextContent("RPC unavailable. Public Set data is still up to date."); });
  it("does not estimate BNB when no wrapped-native pool price is available", () => { const withoutBnbPrice = { ...poolState, contract: undefined } as PoolState; mocks.useWalletPoolPosition.mockReturnValue({ state: { status: "ready", position: { account, assetBalances: [{ assetId: "WBNB", address: wrappedBnb, balance: 0n }, { assetId: "USDT", address: asset, balance: 0n }], blockNumber: 123n, chainId: 97, nativeBalance: 1n * 10n ** 18n, shares: { canClaim: false, locked: 0n, lockedUntil: 0n, totalAttributed: 0n, unlocked: 0n } } } }); render(<PoolUserPosition pool={pool} poolState={withoutBnbPrice} />); expect(screen.getByText("Price unavailable")).toBeVisible(); });
});
